apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "kubedl.fullname" . }}-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "kubedl.fullname" . }}-role
subjects:
  - kind: ServiceAccount
    name: {{ include "kubedl.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}